### ISSUE TITLE
`block in regions': uninitialized constant Vultr::Region (NameError)

### ISSUE THREAD

**Issue by simplytech** [p0deje/vagrant-vultr#4]
Hello!

I tried using this plug-in for the first time as described here https://www.vultr.com/docs/using-vultr-as-your-vagrant-provider but I'm getting the following error:

```
~/tst/vagrant-vulture-test-project >  vagrant up --provider=vultr
Bringing machine 'default' up with 'vultr' provider...
/Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/helpers/client.rb:77:in `block in regions': uninitialized constant Vultr::Region (NameError)
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/helpers/client.rb:137:in `request'
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/helpers/client.rb:77:in `regions'
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/helpers/client.rb:81:in `region_id'
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/helpers/client.rb:38:in `create_server'
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/action/create.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /Volumes/home/alain/.vagrant.d/gems/gems/vagrant-vultr-0.1.1/lib/vagrant-vultr/action/setup_ssh_key.rb:27:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:567:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

- My Vultr.com account is working. I can create the same server manually with the same parameters:    Atlanta, 768 MB RAM, 15 GB SSD, 1.00 TB BW, Ubuntu 14.04 x64

- My Vagrant can create VMs in VirtualBox
- OS X El Capitan 10.11.6
- System ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
- Vagrant 1.8.6
- VirtualBox 5.1.6

Any help would be greatly appreciated.
Thanks!
Alain.

**Comment by chanlvh** [comment]
I've got the same problem since yesterday

**Comment by p0deje** [comment]
Unfortunately I'm not maintaining this plugin anymore, but will be happy to merge pull request fixing this issue.

**Comment by chanlvh** [comment]
@p0deje perhaps you can consider merging #5 to fix this issue? :)
